### ISSUE TITLE
Why do we need to specify engines in `package.json`?

### ISSUE THREAD

**Issue by felipecesr** [clappr/clappr-core#105]
### What do you want to do with Clappr?

I want to install `@clappr/core` in my project using [docusaurus](https://docusaurus.io/) and node 16, but I've gotten the following error:

<img width="898" alt="image" src="https://github.com/clappr/clappr-core/assets/10980841/a9a53441-0b6b-4d34-bcb4-d99906eb6ce5">

### What have you tried so far?

I've tried to install `@clappr/core`, but It's not possible because the minimum supported node version in [docusaurus](https://docusaurus.io/) is 16 and `@clappr/core` expects node 14.

It doesn't make sense because `@clappr/core` should be bundled by the app to run in browsers.

What do you think about remove `engines` property from `package.json`?

**Comment by leaofelipe** [comment]
It's a good idea! Can u create a PR? @felipecesr
