### ISSUE TITLE
The CDN link doesn't work

### ISSUE THREAD

**Issue by sapolio** [clappr/clappr-core#46]
The main file of *core* is not found via this link
https://cdn.jsdelivr.net/npm/clappr/core@latest/dist/clappr-core.min.js

**Comment by jimaek** [comment]
This would be the correct URL in this case https://cdn.jsdelivr.net/npm/@clappr/core@latest/dist/clappr-core.min.js

**Comment by sapolio** [comment]
Thanks, @jimaek !
So, it's a typo in readme file.

**Comment by joaopaulovieira** [comment]
Yes, it's a typo 🤦

**Comment by joaopaulovieira** [comment]
Fixed! Thanks @jimaek !
