### ISSUE TITLE
Tem como adaptar de forma simples com typeScript?

### ISSUE THREAD

**Issue by Apdo3939** [clappr/clappr-core#57]
O que eu queria saber era se tem uma forma simples de adaptar de JS para TS?

**Comment by Ronkiro** [comment]
Sim, tem como!! Mas qual o problema que você está tendo? Acho que você necessita ser um pouco mais específico.

**Comment by Apdo3939** [comment]
Por preferência de linguagem... pois sou do backend e usar c#, c++ e java.  Já consegui! muito obrigado! Eu só tipei as constante que queria ter um pouco mais de controle sobre elas!
